[package]
name = "gotham_examples_openssl"
description = "An example application for using Gotham with OpenSSL"
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../gotham", default-features = false }

futures-preview = "0.3.0-alpha.19"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3"
tokio-openssl = "=0.4.0-alpha.6"
openssl = "0.10"
tokio = "=0.2.0-alpha.6"
failure = "0.1"
