[package]
name = "gotham_examples_hello_world"
description = "A Hello World example application for working with Gotham."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../gotham" }

hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3"
