[package]
name = "gotham_examples_headers_setting"
description = "Setting a header value for a Gotham web framework response"
version = "0.0.0"
authors = ["Eren Güven <erenguven0@gmail.com>"]
publish = false

[dependencies]
gotham = { path = "../../../gotham" }

hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3"
