[package]
name = "gotham_examples_hello_world_until"
description = "A Hello World example application for working with Gotham. With graceful shutdown."
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../gotham" }

futures-preview = "0.3.0-alpha.19"
tokio = "=0.2.0-alpha.6"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3"
tokio-signal = "0.2"

[target.'cfg(unix)'.dev-dependencies]
nix = "0.15"
