[package]
name = "gotham_examples_middleware_multiple_pipelines"
description = "Provides examples of using multiple middleware pipelines for different routes."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
futures-preview = "0.3.0-alpha.19"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
