[package]
name = "gotham_examples_templating_askama"
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }

askama = "0.8.0"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3.12"
