[package]
name = "gotham_examples_middleware_introduction"
description = "Introduces the Middleware and Pipeline concepts provided by the Gotham web framework"
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
futures-preview = "0.3.0-alpha.19"
mime = "0.3"
