[package]
name = "gotham_examples_templating_tera"
description = "A Tera template engine usage example application for Gotham."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }

hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3"
tera = "0.11"
lazy_static = "1.0"
